### ISSUE TITLE
BUG: extrafield at the attribute level are not properly displayed after an edit

### ISSUE THREAD

**Issue by dvasseur** [Dolibarr/dolibarr#13279]
# Bug
After editing an extrafield at the attribute level, the value of the edited extrafield is displayed on all attributes. It's just a display issue, after refreshing the page, the right values are displayed.

## Environment
- **Version**: 9.0.3
- **OS**: Debian 10
- **Web server**: nginx
- **PHP**:  7.3
- **Database**: MariaDB

## Steps to reproduce the behavior
Before editing ('Prix unitaire annuel ...' is my extrafield): 2 values 750 and 1200
![image](https://user-images.githubusercontent.com/6320683/75977213-300a0300-5edc-11ea-9f54-0f152cdf9213.png)

Editing the extrafield for the second attribute, value changed from 1200 to 1400
![image](https://user-images.githubusercontent.com/6320683/75982671-6b5dff00-5ee7-11ea-9e91-a659700197ee.png)

After validating, 1400 displayed on both attributes
![image](https://user-images.githubusercontent.com/6320683/75977369-8e36e600-5edc-11ea-9a34-aeabb2c3fb2e.png)

The bug is here I think, the value is retrieved from the edit params through the GETPOSTISSET() call, even for non-edited attributes
https://github.com/Dolibarr/dolibarr/blob/5a22fb11ef035fd641e12fee34c5195d0fe47018/htdocs/core/class/commonobject.class.php#L6781

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by dvasseur** [comment]
Could you create an extrafield at the attribute level in the 'contract' module on the demo [website](https://demo.dolibarr.org/index.php?urlfrom=%2Fpublic%2Fdemo%2Findex.php&disablemodules=adherent,barcode,bom,cashdesk,don,expedition,externalsite,ftp,incoterm,mailmanspip,margin,mrp,prelevement,product,productbatch,stock,takepos) ? It would help me to test with the latest version.

**Comment by eldy** [comment]
Done

**Comment by dvasseur** [comment]
Indeed, it seems to be fixed on the demo website (12.0-alpha ?)

Do you know if it was fixed on version 10 or 11 ?

**Comment by dvasseur** [comment]
I'm reopening the case since I've just migrated to 12.0.5 and still have the issue :(

Moreover, values are displayed like this now: 900,00000000 (should be 900)
