### ISSUE TITLE
Bug: Discount on already paid invoice impossible

### ISSUE THREAD

**Issue by fpav** [Dolibarr/dolibarr#13303]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 11.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.15
- **Database**: MySQL or MariaDB 5.7.26-log
- **URL(s)**: /compta/facture/card.php?facid=120&action=valid&page_y=514

## Expected and actual behavior
[*Verbose description*]

Normally, we can introduce the discount in the invoice for already paid invoices, but when it is done, we have an error message at validation step.

## Steps to reproduce the behavior
[*Verbose description*]

Introduce a discount for a customer and apply this discount on an invoice. Then when validation occur, error message appear.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

![2020-03-08_14-45-05](https://user-images.githubusercontent.com/58973675/76164038-b9733c80-614b-11ea-8c35-195443759836.jpeg)

**Comment by eldy** [comment]
Fixed by e66313d47e37656d5a1bd5d0483b738b245563ae

**Comment by fpav** [comment]
Sorry, but I changed the line as explained in the card.php file and it doesn’t solve the issue, I still have an error message :

Total of lines can't be negative for a given VAT rate.


And validation of the invoice is not possible.


Franck PAVAN
Eurocom SARL
6, Chemin des Garennes
31260 TOUILLE
T : +33 661 573 000
fpa@red-limo.com
French Partner of iRisk www.irisk.com

**Comment by fpav** [comment]
Solved by Eldy : https://github.com/Dolibarr/dolibarr/commit/88d98acbba9ec104192083e6c349b8508ca95320
