### ISSUE TITLE
Not all bank accounts have IBAN Numbers

### ISSUE THREAD

**Issue by paddatrapper** [Dolibarr/dolibarr#14418]
# Bug
Currently Dolibarr expects all bank accounts to have IBAN numbers. In some countries these are not issued (for example South Africa) and you are unable to create a bank account without inventing an IBAN number or some other placeholder (e.g. we use N/A)

## Environment
- **Version**: 11.0.5
- **OS**: Docker
- **Web server**: Nginx
- **PHP**: 7.3.18
- **Database**: MySQL 10.112.14.175

## Expected and actual behavior
Don't require IBAN for bank accounts

**Comment by dpriskorn** [comment]
Can you check if the problem is present in v12?

**Comment by paddatrapper** [comment]
I seem unable to edit a user's bank account details at all in 12.0.1, so I can't check

**Comment by paddatrapper** [comment]
In 12.0.1:

* Vendor bank accounts - do not require IBAN numbers
* Company bank accounts - do not require IBAN numbers
* Internal Users - Can no longer add or modify bank accounts, so cannot test

**Comment by eldy** [comment]
So my understanding is that it is fixed in 12.0.1, isn't it ?

**Comment by paddatrapper** [comment]
Currently unknown - I cannot test if 12.0.1 fixed it for Internal Users due to #14421

**Comment by paddatrapper** [comment]
This has been fixed. Tested in 13.0.4

**Comment by aljawaid** [comment]
This issue still exists in `/societe/paymentmodes.php`

IBAN and Swift/BIC is still mandatory in Payment Information tab of Dolibarr v14.0.2

**Comment by bos4711** [comment]
Confirmed, issue exist in 14.0.3 as well.

**Comment by bos4711** [comment]
More info: https://www.dolibarr.org/forum/t/dolibarr-enforces-the-use-of-iban-how-to-disable/21351

**Comment by aljawaid** [comment]
Not a fix to the code, but a fix to the problem.  This edit works for 14.0.3 for me.

NEW: add constant MAIN_IBAN_IS_NEVER_MANDATORY https://github.com/Dolibarr/dolibarr/pull/18356
