### ISSUE TITLE
Listing Issue in Proposals

### ISSUE THREAD

**Issue by bugfishtm** [Dolibarr/dolibarr#17767]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 13.0.2 [*Affected Dolibarr version(s)*]
- **OS**: Debian 10 [*Server OS type and version*]
- **Web server**:  Apache 2.4 [*Webserver type and version*]
- **PHP**: 7.4 [*PHP version*]
- **URL(s)**: https://XXXXX/dolibarr/comm/propal/index.php?leftmenu=propals

## Expected and actual behavior
The list in the right on a screen resolution of full hd, showing different costumers in a list.
"Open Proposals und Last edited Proposals"
There is a tooltip is you go over a customer, showing its mail.
Every customer in the left list, shows the mail of the last entry of the customer of the list
"Draft Proposals" on the same page (the url you can see above, the proposal page)

## Steps to reproduce the behavior
-> Go to the link https://192.168.44.41/mitec/comm/propal/index.php?leftmenu=propals
-> Check the Customer Numbers on the List in the Customer Labbel Field (its wrong)
-> Check the Mail add in the Tooltip (its wrong)
There is the value in it with the last entrie in the left list
This is a dolibarr version updated from 12.0.4 to 13.0.2

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]
![Capture](https://user-images.githubusercontent.com/27702527/120074234-331e7f80-c09c-11eb-8047-72ed33b91ffb.JPG)

**Comment by atm-maxime** [comment]
Hi !
Thanks for reporting. Can you try with the last 13.0.4 stable version ? I cannot reproduce so I think it has been fixed.

**Comment by bugfishtm** [comment]
Hi there, 
i tested in 13.0.4 from an installation which was upgraded constantly from 12.0.1.
The issue persists there and does not seem fixed.

But as 14.0.0 is now out stable, i updated another machine to the newest version - and there it seems definitily fixed on 14.0.0 (with upgrade and new installation)

As i will upgrade all versions to 14.0.0 
its okay for me to close this ticket

Thanks for reporting in and have a nice week :)
