### ISSUE TITLE
Issue with import proposal 

### ISSUE THREAD

**Issue by Mmamin72** [Dolibarr/dolibarr#20025]
### Bug

I’m trying to import old proposal, i managed to import Purchase orders with no errors, but when i try to import Puchase order lines i get the follwoing error
1 errors found

Line 2
Unknown column ‘import_key’ in ‘field list’

### Environment Version

14.5

### Environment OS

windows 10 and debain 11

### Attached files

![image](https://user-images.githubusercontent.com/99310017/153125098-fc5d1b51-5bfb-45d0-9426-8fdad7517a18.png)

**Comment by aspangaro** [comment]
Fixed already proposed in #20000 (v14) & #20001 (v15 & higher)

**Comment by Mmamin72** [comment]
Thank you aspangaro 
for your prompt reply, I'm using ver 14.5 and still have this issue

**Comment by priojk** [comment]
The fix is currently _proposed_ for v14 and v15 (but not yet merged/integrated in a published release).

**Comment by Mmamin72** [comment]
is there any estimated date for the release with fix?

**Comment by ksar-ksar** [comment]
No, it is open source world !

**Comment by Mmamin72** [comment]
I'm so sorry as I'm new to this, is this mean i have to download or edit .sql file with new script in the fix. correct?

**Comment by priojk** [comment]
If it's urgent and you are a bit tech savvy (or have someone around) you can try to manually apply the fix. If I didn't misread it, it just creates the missing column: 

`ALTER TABLE llx_propaldet ADD COLUMN import_key varchar(14);`

You can use e.g. phpmyadmin to create this additional column. As usual: try it only in a test environment first and have a backup available...

**Comment by catrielr** [comment]
#18275
