### ISSUE TITLE
The cursor returns to the Cc field when typing the core message of email for invoice

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#24515]
### Bug

When I type the first character in the body message, the cursor jumps to the Cc field.

### Environment Version

16.0.4

### Environment

Linux Mageia
Firefox 102.9ESR

### Environment Web server

Apache

### Environment PHP

7.4

### Environment URL(s)

http://localhost/dolibarr/htdocs/compta/facture/card.php?facid=948&action=presend&mode=init#formmailbeforetitle

### Expected and actual behavior

I expected that the cursor stays in the body frame.

### Steps to reproduce the behavior

In the invoice, asks for email the invoice.
Complete recipient field with predefined contact.
Complete Cc field with predefined contact.
Click in body frame, type a first character. The cursor returns to Cc field.

**Comment by d3v2a** [comment]
Maybe related to this

https://www.dolibarr.fr/forum/t/bug-a-la-creation-dun-nouveau-produit/42129/2

**Comment by AurelienBISOTTI** [comment]
I can reproduce in V17.0.2

Mine goes from CC to TO

![image](https://github.com/Dolibarr/dolibarr/assets/12530585/9bfa270b-fb08-4bfd-b36a-e6b7403ae8b0)

**Comment by AurelienBISOTTI** [comment]
It seems fixed in v18

**Comment by papoteur-mga** [comment]
@Hystepik 
Hello,
No, I have v18.0.4 now, but still the same bug.
