### ISSUE TITLE
Displaying third-party donors in Latest 10 modified donations

### ISSUE THREAD

**Issue by manu-p** [Dolibarr/dolibarr#30424]
### Bug

Following issue [24946](https://github.com/Dolibarr/dolibarr/issues/24946), it appears that when you see the list of the 'Latest 10 modified donations" as per **Donations** page, no third party is shown, just missing here.

### Dolibarr Version

19.0.2

### Environment PHP

8.1

### Environment Database

any

### Steps to reproduce the behavior and expected behavior

Click on **Donations** under the **Billing | Payment** menu and see on the right column under 'Latest 10 modified donations'

### Attached files

In the following snapshot the donators are meant to appear between the donation number and the amount, e.g. 15 and 100.00.
![Capture d’écran du 2024-07-19 17-40-59](https://github.com/user-attachments/assets/d0c2c599-0abc-40ed-abf0-8dd3d012d27b)

**Comment by aspangaro** [comment]
This will apparently be corrected in v20

![image](https://github.com/user-attachments/assets/653d935b-be1d-4756-8646-0c65f0acc2c1)

**Comment by manu-p** [comment]
Hi, could this issue be re-opened since the Third party is still not displayed in the list of the "Latest 10 modified donations", under 20.0.2?
