### ISSUE TITLE
[Barcode] Can't change engine without javascript

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3234]
# Environment
- **Version**: 3.8.0-beta
- **OS**: Linux
- **Web server**: nginx/1.8.0
- **PHP**: fpm-fcgi 5.6.11
- **Database**: MySQL or MariaDB 5.5.5-10.0.20-MariaDB-log
- **URL**: /admin/barcode.php
# Report

Can't change engine without javascript.
A fallback method should be provided!

**Comment by marcosgdf** [comment]
Isn't this more a feature request than a bug?

**Comment by rdoursenaud** [comment]
Working without javascript is not an option but a requirement. So it classifies as a bug in my book.

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ?
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Comment by rdoursenaud** [comment]
@eldy Bug is still present in develop: https://drive.google.com/file/d/0B2ODG5fp26wXdml4QlNqQlY1Rm8/view

**Comment by rdoursenaud** [comment]
Also, with javascript enabled, the configuration is silently saved as soon as the setting is changed which is a bit weird considering that no other part of Dolibarr behaves that way.

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Comment by marcosgdf** [comment]
I have just tested and I see it is still happening under 6.0.4 version

**Comment by hregis** [comment]
Wotk in progress
