### ISSUE TITLE
Dolibarr Version 20.0.1 is unable to restrict users to their own third parties. 

### ISSUE THREAD

**Issue by Dollyogake** [Dolibarr/dolibarr#32441]
### Bug

Dolibarr Version 20.0.1 is unable to restrict users to their own third parties. They can see other users' customers. How can I restrict them to only see their own customer list?

### Dolibarr Version

20.0.1

**Comment by JonBendtsen** [comment]
which permissions does your users have @Dollyogake ?

**Comment by hregis** [comment]
@Dollyogake i think this is fixed for the next version 20.0.3

**Comment by galaxy101quest** [comment]
I'm using version 20.0.3 and the bug is still there - Users can see all third parties in the list - without restriction.
My Permission settings for Third Party has only the following radio button on: "Read third parties linked to user - Not effective for external users (always limited to their third party)". 
 
The only restriction which is currently available is when the user clicks to view details on the third party which is not assigned/belong to him - in that case there's a message "Access denied. You try to access to a page, area or feature of a disabled module or without being in an authenticated session or that is not allowed to your user.". 

However if the third party is not assigned to the user, he/she should not be able to see the full list of all third parties in the platform - that exposes a lot of information.
