### ISSUE TITLE
Bug: Event type dictionnary page is not translated

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4523]
Version: 3.8

![captura de pantalla 2016-01-29 a las 9 32 03](https://cloud.githubusercontent.com/assets/168744/12670754/344ef12c-c66b-11e5-8862-75a6c3b466d0.png)

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Comment by marcosgdf** [comment]
Still happening

![image](https://user-images.githubusercontent.com/168744/34084165-5feb3496-e37c-11e7-99c3-538f5e5b9c33.png)
