### ISSUE TITLE
Bug: Products/Services Quarterly Turnover calculation errors

### ISSUE THREAD

**Issue by hameau** [Dolibarr/dolibarr#4776]
# Bug

The calculation for Products and Services quarterly turnover (MAIN_FEATURES_LEVEL=1, Main Menu: Products/Services) does not take account of multiple payments per invoice, nor deposit payments used as future credit (part payment).
## Environment
- **Version**: 3.8.3 (but previous versions, too)
- **OS**: Debian 8 (Jessie)
- **Web server**: Apache 2.4.10
- **PHP**: 5.6.17
- **Database**: MySQL 5.5.47
- **URL(s)**: /product/index.php?mainmenu=products&leftmenu=
## Expected and actual behaviour

The table is designed to show the quarterly turnover, by Products and Service, together with an annual total, for the previous three (complete?) years. It was originally aimed at auto-entrepreneurs, to provide easy access to turnover figures required for obligatory quarterly reporting (e.g., net-entreprises.fr).

Errors are introduced by:
- **Multiple payments:** If an invoice is settled by, for example, a cheque payment and a cash payment, the **invoice total** is added to the turnover **for each payment**. This is incorrect – each separate **payment amount** should be added to the turnover.
- **Deposit used as payment of final invoice:** In this case, the deposit payment (which is the same value as the deposit invoice) is added to the turnover – this is correct. The final invoice is raised and the deposit is applied as part payment. When the balance of the final invoice is paid, the **total value of the final invoice** is added to the turnover. This is not correct: only the **balance payment** should be added to the turnover.

This results in overstating the turnover.
## Steps to reproduce the behaviour

Multiple payments:
- Raise an invoice and validate it;
- Make a part payment;
- Make a second payment for the balance of the invoice.

Using deposit payment as credit:
- Raise a deposit invoice, validate it and make payment;
- Raise a final invoice, validate it and apply the deposit invoice as a credit, together with payment for the balance of the final invoice.

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Comment by hameau** [comment]
In case of future searchers:

The relevant code is still the same in the current development branch and is still experimental (so unsupported).

I now prefer to use the Auto Micro Entreprise plugin (Dolistore) for this analysis and report.
