### ISSUE TITLE
[Bug] [Fiscal] Error in deposit VAT calculation (French:TVA d'acompte  trimestriel)

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#5372]
Reporting in English and French (partially).

I'll keep the description further below, but after analysis, I conclude that the deposits are registered as products regardless of the origin of the deposit.
As VAT on products is applicable immediately, we have the wrong behavior if the VAT applies to services.
By changing the deposit type to service (in the database), the behavior seems correct.
The best solution is likely to copy the deposit type from the source invoice - possibly one line is needed for service deposits and another line for product deposits.
However as products are not subject to VAT anyway when they are deposits, the best default is to set the type of a deposit to service.  If it is a product, then there is no VAT and there is no effect.  If it is a service, there is VAT, and the behavior is correct.

Original report:
# Bug

VAT on (paid) deposits for a service is substracted from the VAT reports.
This is incorrect because the VAT on the deposit for a service has already been paid and is therefore due.

Example/Exemple:
http://demo.dolibarr.org/compta/facture.php?facid=3720
Report:
http://demo.dolibarr.org/compta/tva/index.php?leftmenu=tax_vat&mainmenu=accountancy

FR:La TVA payé lors de l'acompte pour un service et déduit sur une facture future est déduit des rapports de TVA.  Ceci est incorrect car la TVA payé sur acompte est dû lorsqu'il s'agit d'un acompte pour un service.
## Environment
- **Version**: 3.9.2 and earlier - bug verified in demo.dolibarr.org environment.
## Expected and actual behavior

The deposit taken into account on the (final) invoice should not appear as a negative amount in the vat reports (used to determine the VAT amount due).  Or if it appears, it should immediately be compensated by a positive amount.
FR: La TVA prise en compte pour la facture finale ne devrait pas apparaître comme un montant négatif dans les rapports de TVA.
## Steps to reproduce the behavior

Create a deposit invoice at a past date (Example, 1 month ago).  Amount of the deposit for the service: 100.  Make sure that the VAT is not 0%.
Confirm the deposit invoice.
Pay the deposit invoice at the invoice date.
Convert the deposit invoice in future reduction.
Create a new invoice.
Apply the reduction of the deposit invoice.
Add another line for a service costing for instance 200 excl. VAT.  Make sure that there is VAT on this line.
Confirm the invoice.
Check the VAT report (http://demo.dolibarr.org/compta/tva/index.php?leftmenu=tax_vat&mainmenu=accountancy ).
You will find the VAT amount corresponding to the deposit as a negative amount in the detail and deducted from the total.

Further observation:
A partial payment does not fix the issue.  Only a full payment resolves it.

**Comment by atm-maxime** [comment]
Hello,

You're right there's something we should be able to setup : deposit line is a product or a service.
Today it's a product by default, and the deposit has a 0 VAT rate.

What should we do with a deposit from an order that contains both products and services ? Add 2 deposit lines ? But if the deposit is created with an amount and not a % ?

**Comment by mdeweerd** [comment]
In french - tax rules are a bit complex, http://bofip.impots.gouv.fr/bofip/283-PGP.html#283-PGP_120_094.
I think I have read one time that if it is in majority services, services apply.  However, I'll try to check this.
I think that it is perfectly ok (best) that a proportional rule is used when creating the deposit lines and use this percentage when applying it to the final invoice.
However I am not accountant!

**Comment by eldy** [comment]
Because a deposit invoice is in most case a small part of invoice, there is no way to know the vat (if invoice has several different line, which vat will you use ?). So current practice is to set vat to 0.
However, if you are sure vat is not 0, but 20% for example, vat will be payed because of deposit invoice.
If you don't remove it from final invoice, you will pay it twice.

Can you reproduce the problem (deposit and final invoice that consume the deposit) on demo.dolibarr.org and provide the ref ?

**Comment by mdeweerd** [comment]
Procedure followed:
1. Create customer;
2. Create order https://demo.dolibarr.org/commande/card.php?id=149 with a service ;
3. Validate order.
4. Create deposit invoice for order (30%).
   https://demo.dolibarr.org/compta/facture.php?facid=745
5. VAT value proposed is initially 0%.  Change VAT value to 20% (Theoretically, the VAT value could have been determined based on the fact that the order is for a service).
6. Pay the deposit.
   https://demo.dolibarr.org/compta/paiement/card.php?id=296
7. Convert in future reduction
8. Return to order 
   https://demo.dolibarr.org/commande/card.php?id=149
9. Create final invoice.
   https://demo.dolibarr.org/compta/facture.php?facid=746
10. Apply deposit to final invoice.
    |VAT for deposit is ok in final invoice in current online version].
11. Make partial payment of invoice.
12. Check VAT reports:
    https://demo.dolibarr.org/compta/tva/index.php?leftmenu=tax_vat&mainmenu=accountancy [incorrect, see other issue 5374]
    https://demo.dolibarr.org/compta/tva/quadri_detail.php?leftmenu=tax_vat&month=8&year=2016
    https://demo.dolibarr.org/compta/tva/quadri_detail.php?leftmenu=tax_vat&month=9&year=2016

Issues:
- Deposit payment https://demo.dolibarr.org/compta/facture.php?facid=745 is added and then subtracted from the report for september.  So the net VAT due according to this report is 0 for the deposit (while the VAT collected on the deposit is officially due).
- The deposit is listed as a product - it should be listed as a service.  Even when changing the VAT, the type of the deposit can not be selected.
  If the deposit would be a service, I suspect that the VAT would be considered correctly.
- Only the partial payment of the final invoice is listed as due.

I hope this helps.

**Comment by mdeweerd** [comment]
Also made the final payment (october):
https://demo.dolibarr.org/compta/paiement/card.php?id=298
https://demo.dolibarr.org/compta/tva/quadri_detail.php?leftmenu=tax_vat&month=10&year=2016

We can notice in this report that despite the payment of only 1520€, the "HT collectée" is 1809,52 which includes the VAT of the deposit.
The issue is that the month in which the VAT of the deposit is actually taken into account is invalid with regard to the type of the initial order (service).

The type of the deposit could be determined from the type of the lines in the proposal/order.  Possible two lines need to be created and it may be usefull to indicate "Acompte (service)" and "Acompte (biens)" depending on the deposit type.
As the deposit detail have types in the same way as the other detail lines do, the calculation should be mostly correct once the correct type is applied.

It must be verified though that the negative amount for the service deposit on the final invoice is applied correctly over time.

**Comment by eldy** [comment]
I think all problems are related to same point:
When a deposit line is added into a deposit invoice, it is always with type "product". And as said by reports "- For material assets, it includes the VAT invoices on the basis of the invoice date. - Deposit invoices are included"   (so it does not use the date of payments like it do for services).

When you create a deposit invoice from an order using the "Variable amount (% tot)", the type of line is not requested. It should be here and saved into the line of invoice. Here you deposit invoice has a line with wrong type.

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Comment by mdeweerd** [comment]
IMHO this is not fixed - I just verified the provided procedure which in itself took some effort to write it up exactly.

Checked on current demo (6.0.4):
- Order: https://demo.dolibarr.org/commande/card.php?id=1877
- Deposit invoice: https://demo.dolibarr.org/compta/facture/card.php?facid=5889 
- Final invoice: https://demo.dolibarr.org/compta/facture/card.php?facid=5890 

![image](https://user-images.githubusercontent.com/1504752/33514900-6a32a5e2-d75b-11e7-98d9-1d71d5b12441.png)


One out of three issues are fixed (initial VAT amount).  However that could have introduced another bug.
Here is the list of issues that remain.
Issues:
- Fixed(?):  The initial VAT% is no longer 0 on the generated deposit invoice.  But the line that is created is a product line and on products there is no VAT for deposits.  So this has to be checked (only VAT on deposit for services, not for products);
- The deposit is listed as a product - it should be listed as a service.  
- Only the partial payment of the final invoice is listed as due in the VAT report because the wrong product deposit annihilates itself.

As the issue has been open for more than a year in "Medium" and "Bug" status, I suppose that reopening the issue will not help more to fix it.
I am not reopening an apparently not important bug report.  I know the bug, I pay attention to it when I create a deposit invoice and work around it by deleting the automatic lines and creating the correct lines.

**Comment by mdeweerd** [comment]
We just observed this issue again in 17.0.1 - same as explained in https://github.com/Dolibarr/dolibarr/issues/5372#issuecomment-348685916 .

**Comment by eldy** [comment]
> IMHO this is not fixed - I just verified the provided procedure which in itself took some effort to write it up exactly.
> 
> Checked on current demo (6.0.4):
> 
> * Order: https://demo.dolibarr.org/commande/card.php?id=1877
> * Deposit invoice: https://demo.dolibarr.org/compta/facture/card.php?facid=5889
> * Final invoice: https://demo.dolibarr.org/compta/facture/card.php?facid=5890
> 
> ![image](https://user-images.githubusercontent.com/1504752/33514900-6a32a5e2-d75b-11e7-98d9-1d71d5b12441.png)
> 
> One out of three issues are fixed (initial VAT amount). However that could have introduced another bug. Here is the list of issues that remain. Issues:
> 
> * Fixed(?):  The initial VAT% is no longer 0 on the generated deposit invoice.  But the line that is created is a product line and on products there is no VAT for deposits.  So this has to be checked (only VAT on deposit for services, not for products);

This is the expected behaviour. Sometimes we need a VAT for a deposit invoice, sometimes not. This will depend on a lot of different rules. Only you book keeper can say if you need to apply a vat or not and when. Dolibarr allows the two but by default, this is the most common case.
Not that in France (and europe), for product, the VAT must be introduced also for products 
See https://entreprendre.service-public.fr/vosdroits/F31412#:~:text=Depuis%20le%201er%20janvier,r%C3%A9ception%20de%20la%20facture%20finale.

](https://business.lesechos.fr/entrepreneurs/juridique/18315095-tva-exigible-sur-les-acomptes-des-livraisons-de-biens-346636.php)
> * The deposit is listed as a product - it should be listed as a service.

Why ? A deposit may be a product, above all if this is a deposit to buy a product. The VAT to use must be the VAT of the product.

> * Only the partial payment of the final invoice is listed as due in the VAT report because the wrong product deposit annihilates itself.
> 
> As the issue has been open for more than a year in "Medium" and "Bug" status, I suppose that reopening the issue will not help more to fix it. I am not reopening an apparently not important bug report. I know the bug, I pay attention to it when I create a deposit invoice and work around it by deleting the automatic lines and creating the correct lines.

**Comment by mdeweerd** [comment]
@eldy Merci d'avior pris le temps de répondre.

> This is the expected behaviour. Sometimes we need a VAT for a deposit invoice, sometimes not. This will depend on a lot of different rules. Only you book keeper can say if you need to apply a vat or not and when. Dolibarr allows the two but by default, this is the most common case. Not that in France (and europe), for product, the VAT must be introduced also for products See [https://entreprendre.service-public.fr/vosdroits/F31412#:~:text=Depuis%20le%201er%20janvier,r%C3%A9ception%20de%20la%20facture%20finale.](https://business.lesechos.fr/entrepreneurs/juridique/18315095-tva-exigible-sur-les-acomptes-des-livraisons-de-biens-346636.php)

Different countries, different rules.  Invoices to which no deposit is applied, including the deposit invoices themselves are handled as expected.  Final invoices on which the deposits are substracted do not end up correctly in the VAT reports.  Now sind 1/1/2023 one needs to request a VAT payment also for deposits on products.  That may add an extra level of complexity for product deposits.

> Why ? A deposit may be a product, above all if this is a deposit to buy a product. The VAT to use must be the VAT of the product.

Yes, when the deposit is for a product, then the substraction should be made for a product.
When making the deposit invoice itself, it is possible to indicate if the line is a product or a service.
So when substracting the amount of the deposit invoice on the definitive invoice, this substraction should mirror the type(s) of the original invoice.


The issue is how the VAT of the deposit amount of the final invoice ends up in the monthly VAT report.

In France, when the invoice is for a product the seller has to pay VAT to the tax office regardless of whether the customer paid or not, but it is for a service, then this generally is when the customer paid (I think this is configureable in Dolibarr).


In my case, the deposit was for a service.

The deposit invoice has this deposit amount indicated as a service type.

So the final invoice should indicate this also as a service substraction.
Then the subtracted VAT amount would only appear in the monthly VAT report when the invoice is paid.
However, if the deposit amount had 100 EUR VAT, the service amount 1000 EUR VAT and the total VAT amount of the final invoice is 900 EUR VAT, then -100 EUR VAT appears in the report for the month that the invoice was made, and +1000 EUR when the invoice is paid.

My accountant applies 900 EUR VAT for the month that the invoice was paid.


The UI does not allow changing the type for the invoice lines, so it is whatever the type was when substracting the deposit.



EDIT: j'ai modifié le "product_type" de l'acompte de 0 à 1 dans la BDD et le rapport mensuel est ok dans ce cas là - le comptable et dolibarr sont alors en accord.
