### ISSUE TITLE
[Bug] [Fiscal] VAT overview calculation different from detail for partially paid service

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#5374]
# Bug

The VAT for a partially paid service is used 100% when checking VAT totals per month/trimester (http://demo.dolibarr.org/compta/tva/index.php?leftmenu=tax_vat&mainmenu=accountancy ) and partially when checking detail (http://demo.dolibarr.org/compta/tva/quadri_detail.php?leftmenu=tax_vat&month=8&year=2016 ).
## Environment
- **Version**: 3.9.2 - Tested on demo.dolibarr.org - possibly present since a long time.
## Expected and actual behavior

Partial payment used both for summary report and detailed report.
Links of the summary report pointing to the detailed report should give same result.
## Steps to reproduce the behavior

a. Make sure that the configuration indicates that VAT is due for services when paid/collected.
b. Create a customer invoice of 300 excl. VAT with VAT of 10% at the date of today.  The VAT value is then 30.  Validate the invoice, etc.
c. Pay the invoice next month for the amount of 250.  This pays 22.73 VAT and 227.27 excl. VAT.
d. Go to VAT overview (http://demo.dolibarr.org/compta/tva/index.php?leftmenu=tax_vat&mainmenu=accountancy  ).  Observe that VAT taken into account is 30 [by making the payment next month, it is likely that this invoice is the only one visible].
e. click on the detail (month name for month of invoice).  Observe that the VAT taken into account is 22.73 for the total and the detail.

Conclusions:
- The detail is different from the overview;
- The overview should indicate the value shown in the detail.

**Comment by altairis-tof** [comment]
i confirm the bug; 
one should adapt compta/tva/index.php to partial payments like it's done in compta/tva/quadri_detail.php

**Comment by rdoursenaud** [comment]
At least in france, full VAT is due for the state as soon as it's invoiced so I see this as a feature.
Is this different for you?

**Comment by mdeweerd** [comment]
In France:
- VAT is due for products that are shipped and services that are paid.  There are some special rules (you can choose in some cases regarding the services).
A product must be invoiced when it is shipped and a deposit invoice for products should not have VAT.
A service must be invoiced within a certain delay after it is done and deposit invoices for services should have VAT.  However VAT is only due when the customer paid it.
You can check out [the tax office instructions](http://bofip.impots.gouv.fr/bofip/283-PGP.html#283-PGP_120_094).
- Dolibarr already manages this difference but the VAT totals per month/trimester is wrong while the detailed VAT report is correct.  Both should report the same numbers whatever the rule is.

**Comment by rdoursenaud** [comment]
@mdeweerd Thanks for your reply. I think I understand the issue better now. I've tagged the bug appropriately.

**Comment by patalex74** [comment]
@rdoursenaud 
TVA sur encaissement
Facture client de 1562,40 TTC payée en 500+500+500+62,40
vue balance TVA : 760,40

Vue détaillée par mois :
10,40+80,01,+80,01+80,01+9,98=260,41 -> OK

Merci de votre retour et bonne journée.

**Comment by BebZ** [comment]
Thumbs up for the explanation ;) !!
VAT can be due on invoice OR on cash (when payment is made)
So the detailled view per month is wrong 
when the first option (VAT due on invoice) is chosen in configuration, no ?

**Comment by patalex74** [comment]
Here are screenshots :
![balancetva](https://cloud.githubusercontent.com/assets/25580854/22644732/f6f7f29a-ec63-11e6-9bd8-d3cf9f3dc645.jpg)
![tvamois](https://cloud.githubusercontent.com/assets/25580854/22644738/f92ef4b4-ec63-11e6-8d09-38e7113912fd.jpg)

**Comment by novakin** [comment]
Global view is wrong, detailed view is correct.

**Comment by novakin** [comment]
Anyone found a way to fix this ?

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue

**Comment by novakin** [comment]
This is still not fixed for me with the latest stable version 6.0.3

**Comment by mdeweerd** [comment]
I just checked on the demo (6.0.4).  The issue still exists.

- Overview ok:
https://demo.dolibarr.org/compta/tva/index.php?year=2018
- Detail nok:
https://demo.dolibarr.org/compta/tva/quadri_detail.php?leftmenu=tax_vat&month=2&year=2018
https://demo.dolibarr.org/compta/tva/quadri_detail.php?leftmenu=tax_vat&month=3&year=2018

As the issue has been open for more than a year in "Bug" status without benefiting from a level of importance, I suppose that reopening the issue will not help more to fix it.
I am not reopening an apparently not important bug report. I know the bug, I take it into account when checking the VAT detail for a month.

**Comment by atm-maxime** [comment]
This seems to be fixed in latest version.
Please check and reopen issue if needed.
