### ISSUE TITLE
Bug: Weird behaviour when enabling Batch module

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#5535]
# Bug

This message is shown when enabling batch module.

Module 'ProductBatch' depends on module 'modSupplier' that is missing, so module 'ProductBatch' may not work correclty. Please install module 'modSupplier' or disable module 'ProductBatch' if you want to be safe from any surprise
## Environment
- **Version**: 3.9.2

**Comment by eldy** [comment]
I think this is fixed in 3.9.3. Can you confirm ?

**Comment by marcosgdf** [comment]
Still happening in 3.9.3

![captura de pantalla 2016-07-29 a las 11 51 05](https://cloud.githubusercontent.com/assets/168744/17244553/c1df9f54-5582-11e6-99f8-29f358df892c.png)
