### ISSUE TITLE
Bad price for predefine product

### ISSUE THREAD

**Issue by tomamplius** [Dolibarr/dolibarr#5640]
# Bug

When you edit the "price_ht" textbox object with a price and after you select a predefine product then when you add the product is set with bad price.
## Environment
- **Version**: 3.8.\* and 3.9.*
- **OS**: Linux
- **Web server**: apache
## Steps to reproduce

Create new propal
Add product to the propal
Edit the product and cancel
Add predefine product 

The product added have the price of the first product
## Suggested fix

On dolibarr/htdocs/core/tpl/objectline_create.tpl.php in the function setforpredef()

you need to add the bellow command in the function

jQuery("#price_ht").val("");

Thanks for the fix,

**Comment by tomamplius** [comment]
In the video, price is set to 500 but the good price is 394

**Comment by tomamplius** [comment]
In the video at http://dl.lgy.fr/file.php?h=R20e4148ba8fa8a188718484f5cb75f11
The price is set to 500, but the good price is 394.

**Comment by eldy** [comment]
I think it is solved with 3.9.3. Can you confirm ?

**Comment by tomamplius** [comment]
No, the issue is still here in 3.9.3.
The video is on the 3.9.3.

**Comment by eldy** [comment]
And what about version 4.0.3 ?

**Comment by tomamplius** [comment]
Issue is present in dolibarr 5.0
The input box with id "price_ht" need to be set to empty when a predefine product is select.
The input is hidden but the value is send to the server. If this value is not empty then the price of the  predefine product is not used and the hidden value is use to set the price of the product line in the contract
just add the bold instruction
in dolibarr/htdocs/core/tpl/objectline_create.tpl.php
function setforpredef() {
        console.log("Call setforpredef. We hide some fields");
        jQuery("#select_type").val(-1);
        jQuery("#prod_entry_mode_free").prop('checked',false);
        jQuery("#prod_entry_mode_predef").prop('checked',true);
        jQuery("#price_ht").hide();
        jQuery("#multicurrency_price_ht").hide();
        jQuery("#price_ttc").hide();    // May no exists
        **jQuery("#price_ht").val("");**
        jQuery("#tva_tx").hide();
        jQuery("#buying_price").show();
        //jQuery("#fournprice_predef").show(); // management somewhere else
        jQuery("#title_vat").hide();
        jQuery("#title_up_ht").hide();
        jQuery("#title_up_ht_currency").hide();
        jQuery("#title_up_ttc").hide();
        jQuery("#title_up_ttc_currency").hide();
        jQuery("#np_marginRate").hide();        // May no exists
        jQuery("#np_markRate").hide();  // May no exists
        jQuery(".np_marginRate").hide();        // May no exists
        jQuery(".np_markRate").hide();  // May no exists
        jQuery("#units, #title_units").hide();
}

**Comment by marcosgdf** [comment]
I've just pushed your fix. Thank you!
