### ISSUE TITLE
Payment terms editing not allowed (DB syntax error)

### ISSUE THREAD

**Issue by minigitmax** [Dolibarr/dolibarr#7523]
# Bug
Adding new (or editing existing) payment terms in Home/Setup/Dictionaries fails with DB syntax error, below reported. It seems that blocked translation fields cause error in the database when editing or adding items. A double warning shows up telling "Field "Label" is required; Field "Label on documents" is required.

_Error Details_:
**Database type manager**: mysqli
**Latest database access request error**: SELECT c.rowid as rowid, c.code, c.libelle, c.libelle_facture, c.nbjour, c.type_cdr, c.decalage, c.active, c.sortorder FROM llx_c_payment_term AS c WHERE 1 = 1 ORDER BY sortorder 2, sortorder ASC, code ASC LIMIT 1001
**Return code for latest database access request error**: DB_ERROR_SYNTAX
**Information for latest database access request error**: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '2, sortorder ASC, code ASC LIMIT 1001' at line 1

## Environment
- **Version**: [6.0.1]
- **OS**: [Linux 3.10.102 #15152 SMP Fri Sep 1 11:15:28 CST 2017 x86_64]
- **Web server**: [Apache/2.2.31 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141]
- **PHP**: [5.6.30]
- **Database**: [MariaDB 5.5.54]
- **URL(s)**: [ dolibarr/htdocs/admin/dict.php?sortfield=sortorder&sortorder=&rowid=2&code=30D&&id=12&action=edit&page_y=0]

**Comment by eldy** [comment]
Fixed. Will be available with 6.0.2

**Comment by minigitmax** [comment]
Just updated to 6.0.2 and found that the issue is not completely fixed. Now it's possible to add new "payment terms" without BD syntax errors but it's still not possible to edit and modify existing terms where fields "label" and "label on documents" look constrained by an available translation. When saving the record, a warning appears saying that these two fields are required and it's not possible to apply any change.
