### ISSUE TITLE
Ldap authentication failure since upgrade to 7.0.0

### ISSUE THREAD

**Issue by davlord** [Dolibarr/dolibarr#8413]
# Bug
Ldap authentication failure since upgrade to 7.0.0 (an ldaps authentication in our case)

## Environment
- **Version**: 7.0.0
- **OS**: Debian
- **Web server**: Apache
- **PHP**: 7.2
- **Database**: Postgresql 9

## Expected and actual behavior
Ldap authentication to perform like in 6.0.x versions

## Steps to reproduce the behavior
Configure Dolibarr to perform authentication against an ldaps server :
```
$dolibarr_main_auth_ldap_host='ldaps://domain.com';
$dolibarr_main_auth_ldap_port='636';
```
## Workaround
As the bug seems to stand in the "serverPing" function it can be temporarily fix in bypassing this function if we update it to always return true (file **core/class/ldap.php**) :

>         function serverPing($host, $port=389, $timeout=1)
>         {
>                 return true; //temp fix v7.0.0
>                 $op = @fsockopen($host, $port, $errno, $errstr, $timeout);
>                 if (!$op) return false; //DC is N/A
>                 else {
>                         fclose($op); //explicitly close open socket connection
>                         return true; //DC is up & running, we can safely connect with ldap_connect
>                 }
>         }

**Comment by davlord** [comment]
In addition after taking a look at the code we also note that `$dolibarr_main_auth_ldap_port` is ignored as soon as `$dolibarr_main_auth_ldap_host` value starts with 'ldap*'.

**Comment by hregis** [comment]
@davlord 
doc of php "fsockopen":

hostname
If OpenSSL support is installed, you may prefix the hostname with either ssl:// or tls:// to use an SSL or TLS client connection over TCP/IP to connect to the remote host.

**Comment by davlord** [comment]
@hregis 
Hi Régis, thank you for your help.

Changing `$dolibarr_main_auth_ldap_host` from "ldaps://domain.com" to "ssl://domain.com" does solve the serverPing issue which now returns true, but it leads to a failure of "ldap_connect" function (which works fine with "ldaps://" prefix) :

> ldap_connect(): Could not create session handle: Bad parameter to an ldap routine

**Comment by hregis** [comment]
@davlord 
try with this fixe:

```
function serverPing($host, $port=389, $timeout=1)
{
	if (preg_match('/^ldaps/',$host))
	{
		preg_match('/^ldaps:\/\/([^\/]+)\/?$/', $host, $regs);
		$host = 'ssl://'.$regs[1];
	}

	$op = @fsockopen($host, $port, $errno, $errstr, $timeout);
	if (!$op) return false; //DC is N/A
	else {
		fclose($op); //explicitly close open socket connection
		return true; //DC is up & running, we can safely connect with ldap_connect
	}
}
```

**Comment by davlord** [comment]
@hregis 
Thank you for the fix but serverPing is now failing because of the following code which bascially ignore LDAP port from config if host starts with "ldap*" and performs it on the default port 389. Anyway, returning true just does the trick for the moment, I don't won't to bother you further but just to let you know of the bug so it can be fixed in a future release.

```
  if (preg_match('/^ldap/',$host))
                                {
                                        if ($this->serverPing($host) === true) {
                                                $this->connection = ldap_connect($host);
                                        }
                                        else continue;
                                }
                                else
                                {
                                        if ($this->serverPing($host, $this->serverPort) === true) {
                                                $this->connection = ldap_connect($host,$this->serverPort);
                                        }
                                        else continue;
                                }
```

**Comment by hregis** [comment]
@davlord 
can you replace "if (preg_match('/^ldap/',$host)) {....} else {....}"

with just : 

if ($this->serverPing($host, $this->serverPort) === true) {
	$this->connection = ldap_connect($host,$this->serverPort);
}
else continue;

**Comment by hregis** [comment]
@davlord 
see https://github.com/Dolibarr/dolibarr/pull/8420

**Comment by davlord** [comment]
@hregis 
Thank you the authentication works fine now.

**Comment by hregis** [comment]
@davlord 
please, can you try with tls:// instead ssl:// in serverPing() ?

**Comment by davlord** [comment]
@hregis 
Done, it works fine with ssl:// or tls:// prefix in serverPing().

**Comment by jfefe** [comment]
Thanks for this test! So let's follow https://tools.ietf.org/html/rfc7568 :)

**Comment by fkoessler** [comment]
Ldap authentication is still broken for me on 8.0.0

The only way I found to have serverPing return true is by not using the ssl:// or tls:// prefix.

		// Remove ldaps://
		if (preg_match('/^ldaps:\/\/([^\/]+)\/?$/',$host, $regs)) {
			$host = $regs[1];
		}
		// Remove ldap://
		if (preg_match('/^ldap:\/\/([^\/]+)\/?$/',$host, $regs)) {
			$host = $regs[1];
		}

**Comment by apio-sys** [comment]
Indeed strange behavior. I only use ldaps and also had to remove the ssl:// part and also hardcode the port since it would only ping on 389 by default which I do not allow.

`function serverPing($host, $port=636, $timeout=1)
       {
                // Replace ldaps:// by ssl://
                if (preg_match('/^ldaps:\/\/([^\/]+)\/?$/',$host, $regs)) {
                        //$host = 'ssl://'.$regs[1];
                        $host = $regs[1];
`

It would be more elegant if this can be properly fixed and controlled by params in conf.php. I'm running 8.0.4 by the way.
