### ISSUE TITLE
[Bug] Error call to undefined function dol_convert_file() when tried to enter payment at Expense report Card

### ISSUE THREAD

**Issue by tantee** [Dolibarr/dolibarr#9699]
# Bug
Error "call to undefined function dol_convert_file()" when tried to enter payment at Expense report Card

## Environment
- **Version**: 8.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 7.1
- **Database**: MySQL
- **URL(s)**: http:/{dolibarr_server}/expensereport/payment/payment.php?id=3&action=create

## Steps to reproduce the behavior
1. Create new Expense report from HRM tab
2. Validate, Approve as usual workflow
3. When you try to enter payment by click at "Enter Payment" at Expense report Card, you will get the error as followed.

> Fatal error: Uncaught Error: Call to undefined function dol_convert_file() in /var/www/html/core/lib/functions.lib.php:1433 Stack trace: #0 /var/www/html/expensereport/payment/payment.php(203): dol_banner_tab(Object(ExpenseReport), 'ref', '', 1, 'ref', 'ref', '') #1 {main} thrown in /var/www/html/core/lib/functions.lib.php on line 1433

## Suggested steps
I have  reviewed file "function.lib.php" and suspected that error could be from missing reference (require_once) to file "file.lib.php".

**Comment by atm-maxime** [comment]
Hey, I can't reproduce in 8.0.3, seems to have been fixed. Please check when you can and tell us.

**Comment by tantee** [comment]
I cannot find a release tag 8.0.3 but I tried pull the master branch and the problem is still exist.  The error can be suppressed if the config "MAIN_DISABLE_PDF_THUMBS" is set to 1. However, this config is not default.

**Comment by slaivyn** [comment]
Same problem here with version 8.0.4

> Fatal error: Uncaught Error: Call to undefined function dol_convert_file() in /var/www/html/core/lib/functions.lib.php:1439 Stack trace: #0 /var/www/html/expensereport/payment/payment.php(203): dol_banner_tab(Object(ExpenseReport), 'ref', '', 1, 'ref', 'ref', '') #1 {main} thrown in /var/www/html/core/lib/functions.lib.php on line 1439


*    Version: 8.0.4
*    OS: Linux
*    Web server: Apache
*    PHP: 7.1
*    Database: MySQL
*    URL(s): http:/{dolibarr_server}/expensereport/payment/payment.php?id=1&action=create


Is there any additionnal data I could provide to help solve this bug?
